[package]
name = "learn-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
axum = "0.7.9"
httpc-test = "0.1.10"
serde = "1.0.215"
serde_json = "1.0.133"
tokio = {version= "1.41.1", features = ["full"]}
tower-http = {version = "0.4", features = ["fs"]}
